### ISSUE TITLE
jmu_baseball_utils

### ISSUE THREAD

**Issue by therizzo** [kckelly/ncaa-baseball-database#5]
I was hoping to use this to scrape some stats but I cannot without the jmu_baseball_utils. Any chance you can add them to GitHub or share the data_utils, file_utils, and web_utils code?

Best

**Comment by kckelly** [comment]
Yes, I'll add them later tonight.

**Comment by kckelly** [comment]
I added those files, I tested them quickly on my machine so hopefully they should work. I am interested to see if the file creation methods I used will work for someone else, I had to do a workaround to get the paths to certain files for some reason that I do not currently remember.  Let me know if you have any issues and I should be able to answer any questions you have.

**Comment by therizzo** [comment]
Thank you so much! I'll be playing with it and let you know.

**Comment by therizzo** [comment]
I am sorry it took so long to respond. I tweaked your code to match my local settings and adjust a few minor things. So far it is working great! You saved me a ton of time, thank you!
